# Generated by Django 4.1.4 on 2022-12-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('model', models.CharField(max_length=30)),
                ('variant', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('engine', models.CharField(max_length=25)),
            ],
        ),
    ]
